export const ROUTES = {
  ROOT: "/",
  LOGIN: "login",
  ACCOUNT: "account",
  ADMIN: "admins",
  DOULA: "doulas",
  PACKAGE: "package",
  CLIENT: "client",
  ARTICLE: "article",
  PD_SESSION: "pd-sessions",
  CATEGORIES: "categories",
  VOUCHER: "voucher",
  HELP_DOCS: "help-documents",
  SEARCH_SETTINGS: "search-settings",
};
